server:
  port: 8080

spring:
  config:
    import: classpath:you-cant-see-that.yml
  application:
    name: poet-agent
  datasource:
    url: ${SPRING_DATASOURCE_URL:ENC(74AA8WeNmewtlYjGh4jIWPh8E6cxGrZ0M7zg+1wAfBJLR36B6GTw4cvCfA/EhuZiy0oSbrnGRERv5IxzsxfOFA==)}a
    username: ${SPRING_DATASOURCE_USERNAME:ENC(nOfIk0lODnZFZinDkKMeEX5zHzXpOoIj)}
    password: ${SPRING_DATASOURCE_PASSWORD:ENC(W52dd0i/Q8pT/yEJIKs6Zc/brOr6KjXBPVcwdjoe4g4=)}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    hikari:
      # 连接最大生命周期（毫秒），设置为比数据库超时时间短
      max-lifetime: 900000    # 15分钟（从30分钟减少到15分钟）
      # 连接空闲超时时间
      idle-timeout: 300000    # 5分钟（从10分钟减少到5分钟）
      # 连接验证超时时间
      validation-timeout: 3000  # 3秒（从5秒减少到3秒）
      # 连接测试查询
      connection-test-query: SELECT 1
      # 连接池最小空闲连接数
      minimum-idle: 2         # 从5减少到2
      # 连接池最大连接数
      maximum-pool-size: 10   # 从20减少到10
      # 获取连接超时时间
      connection-timeout: 20000  # 20秒（从30秒减少到20秒）
      # 是否自动提交
      auto-commit: true
      # 新增：连接泄漏检测时间（毫秒）
      leak-detection-threshold: 60000  # 60秒
      # 新增：是否在获取连接时验证连接
      connection-init-sql: SELECT 1
      # 新增：连接池名称，便于监控
      pool-name: HikariCP-PoetAgent
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false


